### ISSUE TITLE
Reaktionsliste ausklappbar machen

### ISSUE THREAD

**Issue by franksfotos** [r0bs/bn#63]
Um effizienter durch die eigene Trinkhistorie zu scrollen, könnte die Liste der Proste/Reaktionen (Wiebke hat mit 27 geprahlt!) verkürzt dargestellt werden. Eventuell nur die letzten (oder ersten?) drei und den Rest optional aufklappbar.

**Comment by r0bs** [comment]
schöne Idee! Gibt's ggf. in anderen Apps Vorbilder für eine derartige Implementierung, die die Affordances klar werden lassen? In der simpelsten Implementierung würde ein Tap auf "27 Reaktionen" diese einblenden bzw. ausblenden (Toggle). Wäre das schon klar genug?

**Comment by r0bs** [comment]
@franksfotos: Könntest du hier bitte nochmal ein nachahmenswertes Vorbild beisteuern?

**Comment by r0bs** [comment]
implemented and in distribution
